from efficieno.old_components.components.table_views.base import TableView
from efficieno.old_components.components.table_views.columns import TableColumn
from demo_project.ontology.planmax_header import PlanMaxHeader


class MasterPlanAllColumns(TableView):
    table_header = "Plan Max Master Plan"
    table_description = "PLan Max Master Plan"

    business_division = TableColumn(PlanMaxHeader.business_division, order=1)
    sales_order_number = TableColumn(PlanMaxHeader.sales_order_number, order=2)
    model_line_so = TableColumn(PlanMaxHeader.model_line_so, order=3)
    project_number = TableColumn(PlanMaxHeader.project_number, order=4)
    sos_item = TableColumn(PlanMaxHeader.sos_item, order=5)
    sos_revision = TableColumn(PlanMaxHeader.sos_revision, order=6)
    mfg_organization = TableColumn(PlanMaxHeader.mfg_organization, order=7)
    std_nstd = TableColumn(PlanMaxHeader.std_nstd, order=8)

    # Order Information
    order_category = TableColumn(PlanMaxHeader.order_category, order=9)
    oc_status = TableColumn(PlanMaxHeader.oc_status, order=10)
    dpr_pending = TableColumn(PlanMaxHeader.dpr_pending, order=11)
    mds_status = TableColumn(PlanMaxHeader.mds_status, order=12)
    order_type = TableColumn(PlanMaxHeader.order_type, order=13)
    order_cancelled = TableColumn(PlanMaxHeader.order_cancelled, order=14)
    system_order_status = TableColumn(PlanMaxHeader.system_order_status, order=15)
    line_item_on_model = TableColumn(PlanMaxHeader.line_item_on_model, order=16)
    order_sub_category = TableColumn(PlanMaxHeader.order_sub_category, order=17)
    sales_order_type = TableColumn(PlanMaxHeader.sales_order_type, order=18)
    order_unit_value = TableColumn(PlanMaxHeader.order_unit_value, order=19)
    order_fulfilled_status = TableColumn(PlanMaxHeader.order_fulfilled_status, order=20)

    # Customer Details
    customer_name = TableColumn(PlanMaxHeader.customer_name, order=21)
    bill_to_country = TableColumn(PlanMaxHeader.bill_to_country, order=22)
    ship_to_state = TableColumn(PlanMaxHeader.ship_to_state, order=23)
    ship_to_country = TableColumn(PlanMaxHeader.ship_to_country, order=24)
    region = TableColumn(PlanMaxHeader.region, order=25)
    bill_to_city = TableColumn(PlanMaxHeader.bill_to_city, order=26)

    # Dates
    planned_del_month = TableColumn(PlanMaxHeader.planned_del_month, order=27)
    prn_delivery_date = TableColumn(PlanMaxHeader.prn_delivery_date, order=28)
    last_drp_date = TableColumn(PlanMaxHeader.last_drp_date, order=29)
    original_contract_delivery_dt = TableColumn(PlanMaxHeader.original_contract_delivery_dt, order=30)
    oc_date = TableColumn(PlanMaxHeader.oc_date, order=31)
    first_mds_date = TableColumn(PlanMaxHeader.first_mds_date, order=32)
    prn_date = TableColumn(PlanMaxHeader.prn_date, order=33)
    plan_eol_mech_date = TableColumn(PlanMaxHeader.plan_eol_mech_date, order=34)
    commission_date = TableColumn(PlanMaxHeader.commission_date, order=35)
    so_date = TableColumn(PlanMaxHeader.so_date, order=36)
    customer_po_date = TableColumn(PlanMaxHeader.customer_po_date, order=37)
    original_contract_del_month = TableColumn(PlanMaxHeader.original_contract_del_month, order=37)
    engg_commt_date = TableColumn(PlanMaxHeader.engg_commt_date, order=38)
    last_mds_date = TableColumn(PlanMaxHeader.last_mds_date, order=39)
    sos_revision_date = TableColumn(PlanMaxHeader.sos_revision_date, order=40)
    di_date = TableColumn(PlanMaxHeader.di_date, order=41)
    fg_date = TableColumn(PlanMaxHeader.fg_date, order=42)
    llbom_release_date = TableColumn(PlanMaxHeader.llbom_release_date, order=43)
    first_drp_date = TableColumn(PlanMaxHeader.first_drp_date, order=44)
    current_cust_cont_del_date = TableColumn(PlanMaxHeader.current_cust_cont_del_date, order=45)
    current_cust_cont_del_month = TableColumn(PlanMaxHeader.current_cust_cont_del_month, order=46)
    orig_commited_del_dt = TableColumn(PlanMaxHeader.orig_commited_del_dt, order=47)
    invoice_date = TableColumn(PlanMaxHeader.invoice_date, order=48)
    site_release_date = TableColumn(PlanMaxHeader.site_release_date, order=49)
    fg_pp_date = TableColumn(PlanMaxHeader.fg_pp_date, order=50)
    planned_eol_eni_date = TableColumn(PlanMaxHeader.planned_eol_eni_date, order=51)
    suggested_plan_date = TableColumn(PlanMaxHeader.suggested_plan_date, order=52)

    # Invocie Data
    invoice_number = TableColumn(PlanMaxHeader.invoice_number, order=53)
    planned_invoice_date = TableColumn(PlanMaxHeader.planned_invoice_date, order=54)
    regional_commercial = TableColumn(PlanMaxHeader.regional_commercial, order=55)
    insurance_by = TableColumn(PlanMaxHeader.insurance_by, order=56)
    abp_percent = TableColumn(PlanMaxHeader.abp_percent, order=57)
    pgb_percent = TableColumn(PlanMaxHeader.pgb_percent, order=58)
    penalty = TableColumn(PlanMaxHeader.penalty, order=59)
    invoiced_value = TableColumn(PlanMaxHeader.invoiced_value, order=60)
    order_currency = TableColumn(PlanMaxHeader.order_currency, order=61)
    transport_scope = TableColumn(PlanMaxHeader.transport_scope, order=62)
    freight_pay = TableColumn(PlanMaxHeader.freight_pay, order=63)
    planned_invoice_value = TableColumn(PlanMaxHeader.planned_invoice_value, order=64)
    total_order_value = TableColumn(PlanMaxHeader.total_order_value, order=65)

    # Thermax Details
    ho_order_to_sales_order = TableColumn(PlanMaxHeader.ho_order_to_sales_order, order=66)
    project_specific_llbom = TableColumn(PlanMaxHeader.project_specific_llbom, order=67)
    job_folder_release_date = TableColumn(PlanMaxHeader.job_folder_release_date, order=68)
    dpr_planned_items = TableColumn(PlanMaxHeader.dpr_planned_items, order=69)
    contract_plan_otp = TableColumn(PlanMaxHeader.contract_plan_otp, order=70)
    ho_order_commited_to = TableColumn(PlanMaxHeader.ho_order_commited_to, order=71)
    di_value = TableColumn(PlanMaxHeader.di_value, order=72)
    brief_scope = TableColumn(PlanMaxHeader.brief_scope, order=73)
    sales_engineer = TableColumn(PlanMaxHeader.sales_engineer, order=74)
    prn_applicable = TableColumn(PlanMaxHeader.prn_applicable, order=75)
    oc_required = TableColumn(PlanMaxHeader.oc_required, order=76)
    ld_applicable = TableColumn(PlanMaxHeader.ld_applicable, order=77)
    fg_month_change_remarks = TableColumn(PlanMaxHeader.fg_month_change_remarks, order=78)
    inco_terms = TableColumn(PlanMaxHeader.inco_terms, order=79)
    technical_ocl = TableColumn(PlanMaxHeader.technical_ocl, order=80)
    product_model = TableColumn(PlanMaxHeader.product_model, order=81)
    oc_closure_date = TableColumn(PlanMaxHeader.oc_closure_date, order=82)
    prn_no = TableColumn(PlanMaxHeader.prn_no, order=83)
    shop_sub_contract = TableColumn(PlanMaxHeader.shop_sub_contract, order=84)
    total_payment = TableColumn(PlanMaxHeader.total_payment, order=85)

    # Other info
    per_po_closed = TableColumn(PlanMaxHeader.per_po_closed, order=86)
    reason_for_otp = TableColumn(PlanMaxHeader.reason_for_otp, order=87)
    original_project_number = TableColumn(PlanMaxHeader.original_project_number, order=88)
    bonus = TableColumn(PlanMaxHeader.bonus, order=89)
    planner = TableColumn(PlanMaxHeader.planner, order=90)
    curr_order_execution_status = TableColumn(PlanMaxHeader.curr_order_execution_status, order=91)
    oc_number = TableColumn(PlanMaxHeader.oc_number, order=92)
    per_dj_closed = TableColumn(PlanMaxHeader.per_dj_closed, order=93)
    di_number = TableColumn(PlanMaxHeader.di_number, order=94)
    send_mail = TableColumn(PlanMaxHeader.send_mail, order=95)
    fuel_type = TableColumn(PlanMaxHeader.fuel_type, order=96)
    tech_clarity_date = TableColumn(PlanMaxHeader.tech_clarity_date, order=97)
    ll_pr = TableColumn(PlanMaxHeader.ll_pr, order=98)
    sos_item_count = TableColumn(PlanMaxHeader.sos_item_count, order=99)
    inspection_required = TableColumn(PlanMaxHeader.inspection_required, order=100)
    tca = TableColumn(PlanMaxHeader.tca, order=101)
    shell_boiler_appr_authority = TableColumn(PlanMaxHeader.shell_boiler_appr_authority, order=102)
    rated_standard_man_hrs = TableColumn(PlanMaxHeader.rated_standard_man_hrs, order=103)
    folder_status = TableColumn(PlanMaxHeader.folder_status, order=104)
    delivery_otp = TableColumn(PlanMaxHeader.delivery_otp, order=105)
